"""Deterministic anchoring oracle: lexical-only anchor and OKF checks."""

from anchor_oracle.core import (
    SCHEMA_VERSION,
    Anchor,
    AnchorCheck,
    AnchorOracleError,
    CircularDenylistInvalid,
    EmptyWiki,
    FixtureDirty,
    FixtureHeadUnverifiable,
    FixtureMissing,
    FixtureShaMismatch,
    FrontmatterIssue,
    FrontmatterValidation,
    MalformedAnchor,
    UnreadableInput,
    WikiMissing,
    canonical_bytes,
    check_anchor,
    evaluate_page,
    evaluate_wiki,
    extract_anchors,
    validate_okf_frontmatter,
    verify_fixture_head,
)

__all__ = [
    "SCHEMA_VERSION",
    "Anchor",
    "AnchorCheck",
    "AnchorOracleError",
    "CircularDenylistInvalid",
    "EmptyWiki",
    "FixtureDirty",
    "FixtureHeadUnverifiable",
    "FixtureMissing",
    "FixtureShaMismatch",
    "FrontmatterIssue",
    "FrontmatterValidation",
    "MalformedAnchor",
    "UnreadableInput",
    "WikiMissing",
    "canonical_bytes",
    "check_anchor",
    "evaluate_page",
    "evaluate_wiki",
    "extract_anchors",
    "validate_okf_frontmatter",
    "verify_fixture_head",
]
